/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSitesRouteImport } from './routes/dashboard/sites'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardPuzzlesRouteImport } from './routes/dashboard/puzzles'
import { Route as DashboardImageSetsRouteImport } from './routes/dashboard/image-sets'
import { Route as DashboardAudioRouteImport } from './routes/dashboard/audio'
import { Route as DashboardSitesIndexRouteImport } from './routes/dashboard/sites/index'
import { Route as DashboardPuzzlesIndexRouteImport } from './routes/dashboard/puzzles/index'
import { Route as DashboardImageSetsIndexRouteImport } from './routes/dashboard/image-sets/index'
import { Route as DashboardAudioIndexRouteImport } from './routes/dashboard/audio/index'
import { Route as DashboardSitesSiteIdRouteImport } from './routes/dashboard/sites/$siteId'
import { Route as DashboardPuzzlesNewRouteImport } from './routes/dashboard/puzzles/new'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSitesRoute = DashboardSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPuzzlesRoute = DashboardPuzzlesRouteImport.update({
  id: '/puzzles',
  path: '/puzzles',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardImageSetsRoute = DashboardImageSetsRouteImport.update({
  id: '/image-sets',
  path: '/image-sets',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAudioRoute = DashboardAudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSitesIndexRoute = DashboardSitesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSitesRoute,
} as any)
const DashboardPuzzlesIndexRoute = DashboardPuzzlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardPuzzlesRoute,
} as any)
const DashboardImageSetsIndexRoute = DashboardImageSetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardImageSetsRoute,
} as any)
const DashboardAudioIndexRoute = DashboardAudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAudioRoute,
} as any)
const DashboardSitesSiteIdRoute = DashboardSitesSiteIdRouteImport.update({
  id: '/$siteId',
  path: '/$siteId',
  getParentRoute: () => DashboardSitesRoute,
} as any)
const DashboardPuzzlesNewRoute = DashboardPuzzlesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardPuzzlesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/reset': typeof ResetRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/dashboard/audio': typeof DashboardAudioRouteWithChildren
  '/dashboard/image-sets': typeof DashboardImageSetsRouteWithChildren
  '/dashboard/puzzles': typeof DashboardPuzzlesRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/sites': typeof DashboardSitesRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/puzzles/new': typeof DashboardPuzzlesNewRoute
  '/dashboard/sites/$siteId': typeof DashboardSitesSiteIdRoute
  '/dashboard/audio/': typeof DashboardAudioIndexRoute
  '/dashboard/image-sets/': typeof DashboardImageSetsIndexRoute
  '/dashboard/puzzles/': typeof DashboardPuzzlesIndexRoute
  '/dashboard/sites/': typeof DashboardSitesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset': typeof ResetRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/puzzles/new': typeof DashboardPuzzlesNewRoute
  '/dashboard/sites/$siteId': typeof DashboardSitesSiteIdRoute
  '/dashboard/audio': typeof DashboardAudioIndexRoute
  '/dashboard/image-sets': typeof DashboardImageSetsIndexRoute
  '/dashboard/puzzles': typeof DashboardPuzzlesIndexRoute
  '/dashboard/sites': typeof DashboardSitesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/reset': typeof ResetRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/dashboard/audio': typeof DashboardAudioRouteWithChildren
  '/dashboard/image-sets': typeof DashboardImageSetsRouteWithChildren
  '/dashboard/puzzles': typeof DashboardPuzzlesRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/sites': typeof DashboardSitesRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/puzzles/new': typeof DashboardPuzzlesNewRoute
  '/dashboard/sites/$siteId': typeof DashboardSitesSiteIdRoute
  '/dashboard/audio/': typeof DashboardAudioIndexRoute
  '/dashboard/image-sets/': typeof DashboardImageSetsIndexRoute
  '/dashboard/puzzles/': typeof DashboardPuzzlesIndexRoute
  '/dashboard/sites/': typeof DashboardSitesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/reset'
    | '/signup'
    | '/verify'
    | '/dashboard/audio'
    | '/dashboard/image-sets'
    | '/dashboard/puzzles'
    | '/dashboard/settings'
    | '/dashboard/sites'
    | '/dashboard/'
    | '/dashboard/puzzles/new'
    | '/dashboard/sites/$siteId'
    | '/dashboard/audio/'
    | '/dashboard/image-sets/'
    | '/dashboard/puzzles/'
    | '/dashboard/sites/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset'
    | '/signup'
    | '/verify'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/puzzles/new'
    | '/dashboard/sites/$siteId'
    | '/dashboard/audio'
    | '/dashboard/image-sets'
    | '/dashboard/puzzles'
    | '/dashboard/sites'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/reset'
    | '/signup'
    | '/verify'
    | '/dashboard/audio'
    | '/dashboard/image-sets'
    | '/dashboard/puzzles'
    | '/dashboard/settings'
    | '/dashboard/sites'
    | '/dashboard/'
    | '/dashboard/puzzles/new'
    | '/dashboard/sites/$siteId'
    | '/dashboard/audio/'
    | '/dashboard/image-sets/'
    | '/dashboard/puzzles/'
    | '/dashboard/sites/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetRoute: typeof ResetRoute
  SignupRoute: typeof SignupRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sites': {
      id: '/dashboard/sites'
      path: '/sites'
      fullPath: '/dashboard/sites'
      preLoaderRoute: typeof DashboardSitesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/puzzles': {
      id: '/dashboard/puzzles'
      path: '/puzzles'
      fullPath: '/dashboard/puzzles'
      preLoaderRoute: typeof DashboardPuzzlesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/image-sets': {
      id: '/dashboard/image-sets'
      path: '/image-sets'
      fullPath: '/dashboard/image-sets'
      preLoaderRoute: typeof DashboardImageSetsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/audio': {
      id: '/dashboard/audio'
      path: '/audio'
      fullPath: '/dashboard/audio'
      preLoaderRoute: typeof DashboardAudioRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sites/': {
      id: '/dashboard/sites/'
      path: '/'
      fullPath: '/dashboard/sites/'
      preLoaderRoute: typeof DashboardSitesIndexRouteImport
      parentRoute: typeof DashboardSitesRoute
    }
    '/dashboard/puzzles/': {
      id: '/dashboard/puzzles/'
      path: '/'
      fullPath: '/dashboard/puzzles/'
      preLoaderRoute: typeof DashboardPuzzlesIndexRouteImport
      parentRoute: typeof DashboardPuzzlesRoute
    }
    '/dashboard/image-sets/': {
      id: '/dashboard/image-sets/'
      path: '/'
      fullPath: '/dashboard/image-sets/'
      preLoaderRoute: typeof DashboardImageSetsIndexRouteImport
      parentRoute: typeof DashboardImageSetsRoute
    }
    '/dashboard/audio/': {
      id: '/dashboard/audio/'
      path: '/'
      fullPath: '/dashboard/audio/'
      preLoaderRoute: typeof DashboardAudioIndexRouteImport
      parentRoute: typeof DashboardAudioRoute
    }
    '/dashboard/sites/$siteId': {
      id: '/dashboard/sites/$siteId'
      path: '/$siteId'
      fullPath: '/dashboard/sites/$siteId'
      preLoaderRoute: typeof DashboardSitesSiteIdRouteImport
      parentRoute: typeof DashboardSitesRoute
    }
    '/dashboard/puzzles/new': {
      id: '/dashboard/puzzles/new'
      path: '/new'
      fullPath: '/dashboard/puzzles/new'
      preLoaderRoute: typeof DashboardPuzzlesNewRouteImport
      parentRoute: typeof DashboardPuzzlesRoute
    }
  }
}

interface DashboardAudioRouteChildren {
  DashboardAudioIndexRoute: typeof DashboardAudioIndexRoute
}

const DashboardAudioRouteChildren: DashboardAudioRouteChildren = {
  DashboardAudioIndexRoute: DashboardAudioIndexRoute,
}

const DashboardAudioRouteWithChildren = DashboardAudioRoute._addFileChildren(
  DashboardAudioRouteChildren,
)

interface DashboardImageSetsRouteChildren {
  DashboardImageSetsIndexRoute: typeof DashboardImageSetsIndexRoute
}

const DashboardImageSetsRouteChildren: DashboardImageSetsRouteChildren = {
  DashboardImageSetsIndexRoute: DashboardImageSetsIndexRoute,
}

const DashboardImageSetsRouteWithChildren =
  DashboardImageSetsRoute._addFileChildren(DashboardImageSetsRouteChildren)

interface DashboardPuzzlesRouteChildren {
  DashboardPuzzlesNewRoute: typeof DashboardPuzzlesNewRoute
  DashboardPuzzlesIndexRoute: typeof DashboardPuzzlesIndexRoute
}

const DashboardPuzzlesRouteChildren: DashboardPuzzlesRouteChildren = {
  DashboardPuzzlesNewRoute: DashboardPuzzlesNewRoute,
  DashboardPuzzlesIndexRoute: DashboardPuzzlesIndexRoute,
}

const DashboardPuzzlesRouteWithChildren =
  DashboardPuzzlesRoute._addFileChildren(DashboardPuzzlesRouteChildren)

interface DashboardSitesRouteChildren {
  DashboardSitesSiteIdRoute: typeof DashboardSitesSiteIdRoute
  DashboardSitesIndexRoute: typeof DashboardSitesIndexRoute
}

const DashboardSitesRouteChildren: DashboardSitesRouteChildren = {
  DashboardSitesSiteIdRoute: DashboardSitesSiteIdRoute,
  DashboardSitesIndexRoute: DashboardSitesIndexRoute,
}

const DashboardSitesRouteWithChildren = DashboardSitesRoute._addFileChildren(
  DashboardSitesRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAudioRoute: typeof DashboardAudioRouteWithChildren
  DashboardImageSetsRoute: typeof DashboardImageSetsRouteWithChildren
  DashboardPuzzlesRoute: typeof DashboardPuzzlesRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSitesRoute: typeof DashboardSitesRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAudioRoute: DashboardAudioRouteWithChildren,
  DashboardImageSetsRoute: DashboardImageSetsRouteWithChildren,
  DashboardPuzzlesRoute: DashboardPuzzlesRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSitesRoute: DashboardSitesRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetRoute: ResetRoute,
  SignupRoute: SignupRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
