/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as DashboardRouteImport } from "./routes/dashboard";
import { Route as DashboardIndexRouteImport } from "./routes/dashboard/index";
import { Route as DashboardSitesRouteImport } from "./routes/dashboard/sites";
import { Route as DashboardSitesSiteIdRouteImport } from "./routes/dashboard/sites/$siteId";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as LoginRouteImport } from "./routes/login";

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardSitesRoute = DashboardSitesRouteImport.update({
  id: "/sites",
  path: "/sites",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardSitesSiteIdRoute = DashboardSitesSiteIdRouteImport.update({
  id: "/$siteId",
  path: "/$siteId",
  getParentRoute: () => DashboardSitesRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRouteWithChildren;
  "/login": typeof LoginRoute;
  "/dashboard/sites": typeof DashboardSitesRouteWithChildren;
  "/dashboard/": typeof DashboardIndexRoute;
  "/dashboard/sites/$siteId": typeof DashboardSitesSiteIdRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/dashboard/sites": typeof DashboardSitesRouteWithChildren;
  "/dashboard": typeof DashboardIndexRoute;
  "/dashboard/sites/$siteId": typeof DashboardSitesSiteIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRouteWithChildren;
  "/login": typeof LoginRoute;
  "/dashboard/sites": typeof DashboardSitesRouteWithChildren;
  "/dashboard/": typeof DashboardIndexRoute;
  "/dashboard/sites/$siteId": typeof DashboardSitesSiteIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/dashboard"
    | "/login"
    | "/dashboard/sites"
    | "/dashboard/"
    | "/dashboard/sites/$siteId";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/login"
    | "/dashboard/sites"
    | "/dashboard"
    | "/dashboard/sites/$siteId";
  id:
    | "__root__"
    | "/"
    | "/dashboard"
    | "/login"
    | "/dashboard/sites"
    | "/dashboard/"
    | "/dashboard/sites/$siteId";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DashboardRoute: typeof DashboardRouteWithChildren;
  LoginRoute: typeof LoginRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/": {
      id: "/dashboard/";
      path: "/";
      fullPath: "/dashboard/";
      preLoaderRoute: typeof DashboardIndexRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/dashboard/sites": {
      id: "/dashboard/sites";
      path: "/sites";
      fullPath: "/dashboard/sites";
      preLoaderRoute: typeof DashboardSitesRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/dashboard/sites/$siteId": {
      id: "/dashboard/sites/$siteId";
      path: "/$siteId";
      fullPath: "/dashboard/sites/$siteId";
      preLoaderRoute: typeof DashboardSitesSiteIdRouteImport;
      parentRoute: typeof DashboardSitesRoute;
    };
  }
}

interface DashboardSitesRouteChildren {
  DashboardSitesSiteIdRoute: typeof DashboardSitesSiteIdRoute;
}

const DashboardSitesRouteChildren: DashboardSitesRouteChildren = {
  DashboardSitesSiteIdRoute: DashboardSitesSiteIdRoute,
};

const DashboardSitesRouteWithChildren = DashboardSitesRoute._addFileChildren(
  DashboardSitesRouteChildren,
);

interface DashboardRouteChildren {
  DashboardSitesRoute: typeof DashboardSitesRouteWithChildren;
  DashboardIndexRoute: typeof DashboardIndexRoute;
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardSitesRoute: DashboardSitesRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
};

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
